name: mindustry
base: core20
adopt-info: mindustry
summary: A sandbox tower defense game
description: |
  Mindustry is a hybrid tower-defense sandbox factory game. Create elaborate
  supply chains of conveyor belts to feed ammo into your turrets, produce
  materials to use for building, and defend your structures from waves of
  enemies. Features include a map editor, 24 built-in maps, cross-platform
  multiplayer and large-scale PvP unit battles.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  mindustry:
    command-chain: ["snap/command-chain/alsa-launch", "bin/desktop-launch"]
    command: bin/launcher
    plugs:
      - alsa
      - network
      - network-bind
      - opengl
      - home
      - joystick
      - pulseaudio
      - desktop
      - wayland
      - x11
      - desktop-legacy
      - unity7
    environment:
      XDG_DATA_HOME: "$SNAP/usr/share"
      GVFS_MOUNTABLE_DIR: "$SNAP/usr/share/gvfs/mounts"
      GVFS_MONITOR_DIR: "$SNAP/usr/share/gvfs/remote-volume-monitors"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  # build-trigger:
  #   source: https://github.com/Anuken/Mindustry.git
  #   plugin: nil
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
  mindustry:
    after: [desktop-gtk2,alsa-mixin]
    plugin: nil
    source: https://github.com/Anuken/Mindustry.git
    override-build: |
      # Get the latest releases json
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/Anuken/Mindustry/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      JAR_URL=$(cat releases.json | jq -r ".[0].assets[] | select(.name | test(\"jar\")) | .browser_download_url" | grep -v "server-release")
      echo "Downloading ${JAR_URL}..."
      wget --quiet "${JAR_URL}" -O "${SNAPCRAFT_PART_INSTALL}/Mindustry.jar"
      rm -f releases.json 2>/dev/null
      snapcraftctl set-version "$VERSION"
    build-packages:
      - wget
      - jq
      - sed
      - openjdk-14-jdk-headless
    stage-packages:
      - openjdk-14-jre-headless
      - ca-certificates
      - ca-certificates-java
      - libpulse0
      - libpulsedsp
      - libxxf86vm1
      - libgl1-mesa-dri
      - libglu1-mesa
      - libgl1-mesa-glx
      - libgles2-mesa
      - x11-xserver-utils
    prime:
        - -usr/lib/jvm/java-*/lib/security/cacerts
        - -usr/lib/jvm/java-*/jre/lib/security/cacerts
  launcher:
    plugin: dump
    source: snap/local
    organize:
      'launcher': 'bin/'
      'padsp': 'bin/'
      'sensible-browser': 'bin/'
      'usr/lib/*/gvfs/*.so': 'usr/lib'
      'usr/bin/xprop': 'usr/bin/xprop.disabled'
  desktop-gtk2:
    build-packages:
      - build-essential
      - libgtk2.0-dev
    make-parameters:
      - FLAVOR=gtk2
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
      - ibus-gtk
      - libibus-1.0-5
